const iconsObj = {
    'meal': [
        'fas fa-mug-hot',
        'fas fa-apple-alt',
        'fas fa-wine-bottle',
        'fas fa-pepper-hot',
        'fas fa-drumstick-bite',
        'fas fa-bread-slice',
        'fas fa-hotdog',
        'fas fa-ice-cream',
        'fas fa-pizza-slice',
        'fas fa-apple-alt',
        'fas fa-carrot',
        'fas fa-glass-cheers',
        'fas fa-palette',
        'fas fa-mug-hot',
        'fas fa-apple-alt',
        'fas fa-wine-bottle',
        'fas fa-pepper-hot',
        'fas fa-drumstick-bite',
        'fas fa-bread-slice',
        'fas fa-hotdog',
        'fas fa-ice-cream',
        'fas fa-pizza-slice',
        'fas fa-apple-alt',
        'fas fa-carrot',
        'fas fa-glass-cheers',
        'fas fa-palette',
        'fas fa-mug-hot',
        'fas fa-apple-alt',
        'fas fa-wine-bottle',
        'fas fa-pepper-hot',
        'fas fa-drumstick-bite',
        'fas fa-bread-slice',
        'fas fa-hotdog',
        'fas fa-ice-cream',
        'fas fa-pizza-slice',
        'fas fa-apple-alt',
        'fas fa-carrot',
        'fas fa-glass-cheers',
        'fas fa-palette',
        'fas fa-mug-hot',
        'fas fa-apple-alt',
        'fas fa-wine-bottle',
        'fas fa-pepper-hot',
        'fas fa-drumstick-bite',
        'fas fa-bread-slice',
        'fas fa-hotdog',
        'fas fa-ice-cream',
        'fas fa-pizza-slice',
        'fas fa-apple-alt',
        'fas fa-carrot',
        'fas fa-glass-cheers',
        'fas fa-palette',
        'fas fa-mug-hot',
        'fas fa-apple-alt',
        'fas fa-wine-bottle',
        'fas fa-pepper-hot',
        'fas fa-drumstick-bite',
        'fas fa-bread-slice',
        'fas fa-hotdog',
        'fas fa-ice-cream',
        'fas fa-pizza-slice',
        'fas fa-apple-alt',
        'fas fa-carrot',
        'fas fa-glass-cheers',
        'fas fa-palette',
        'fas fa-mug-hot',
        'fas fa-apple-alt',
        'fas fa-wine-bottle',
        'fas fa-pepper-hot',
        'fas fa-drumstick-bite',
        'fas fa-bread-slice',
        'fas fa-hotdog',
        'fas fa-ice-cream',
        'fas fa-pizza-slice',
        'fas fa-apple-alt',
        'fas fa-carrot',
        'fas fa-glass-cheers',
        'fas fa-palette',
        'fas fa-mug-hot',
        'fas fa-apple-alt',
        'fas fa-wine-bottle',
        'fas fa-pepper-hot',
        'fas fa-drumstick-bite',
        'fas fa-bread-slice',
        'fas fa-hotdog',
        'fas fa-ice-cream',
        'fas fa-pizza-slice',
        'fas fa-apple-alt',
        'fas fa-carrot',
        'fas fa-glass-cheers',
        'fas fa-palette',
        'fas fa-mug-hot',
        'fas fa-apple-alt',
        'fas fa-wine-bottle',
        'fas fa-pepper-hot',
        'fas fa-drumstick-bite',
        'fas fa-bread-slice',
        'fas fa-hotdog',
        'fas fa-ice-cream',
        'fas fa-pizza-slice',
        'fas fa-apple-alt',
         
         
    ],
    'colors': [
        '#d0a775',
        '#66CC33',
        '#722F37',
        'red',
        '#c66b27',
        '#CD853F',
        '#A52A2A',
        '#FF1493',
        '#8F6C2A',
        '#66CC33',
        '#ed9121',
        '#722f37',
        '#ffa600',
        '#d0a775',
        '#66CC33',
        '#722F37',
        'red',
        '#c66b27',
        '#CD853F',
        '#A52A2A',
        '#FF1493',
        '#8F6C2A',
        '#66CC33',
        '#ed9121',
        '#722f37',
        '#ffa600',
        '#d0a775',
        '#66CC33',
        '#722F37',
        'red',
        '#c66b27',
        '#CD853F',
        '#A52A2A',
        '#FF1493',
        '#8F6C2A',
        '#66CC33',
        '#ed9121',
        '#722f37',
        '#ffa600',
        '#d0a775',
        '#66CC33',
        '#722F37',
        'red',
        '#c66b27',
        '#CD853F',
        '#A52A2A',
        '#FF1493',
        '#8F6C2A',
        '#66CC33',
        '#ed9121',
        '#722f37',
        '#ffa600',
        '#d0a775',
        '#66CC33',
        '#722F37',
        'red',
        '#c66b27',
        '#CD853F',
        '#A52A2A',
        '#FF1493',
        '#8F6C2A',
        '#66CC33',
        '#ed9121',
        '#722f37',
        '#ffa600',
        '#d0a775',
        '#66CC33',
        '#722F37',
        'red',
        '#c66b27',
        '#CD853F',
        '#A52A2A',
        '#FF1493',
        '#8F6C2A',
        '#66CC33',
        '#ed9121',
        '#722f37',
        '#ffa600',
        '#d0a775',
        '#66CC33',
        '#722F37',
        'red',
        '#c66b27',
        '#CD853F',
        '#A52A2A',
        '#FF1493',
        '#8F6C2A',
        '#66CC33',
        '#ed9121',
        '#722f37',
        '#ffa600',
        '#d0a775',
        '#66CC33',
        '#722F37',
        'red',
        '#c66b27',
        '#CD853F',
        '#A52A2A',
        '#FF1493',
        '#8F6C2A',
        '#66CC33',
         
    ]
}

export default iconsObj